[package]
name = "anytls"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "anytls-server"
path = "bin/server.rs"

[[bin]]
name = "anytls-client"
path = "bin/client.rs"

[dependencies]
bytes = "1.12.1"
clap = { version = "4.6.7", features = ["derive", "wrap_help"] }
env_logger = "0.11.11"
log = { version = "0.4.34", features = ["serde"] }
md-5 = "0.11.0"
rand = "0.10.3"
rcgen = "0.14.10"
rustls = "0.23.45"
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.11.0"
socks-hub = { version = "0.2.9", default-features = false, features = [
    "httpproxy",
] }
socks5-impl = { version = "0.9.6", features = ["server", "serde"] }
tokio = { version = "1.53.1", features = [
    "fs",
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-rustls = "0.26.5"
tokio-util = { version = "0.7.19", features = ["rt"] }
